let car:  string = "subaru";
console.log(`/n first five tests is true`);
//test 1;
console.log(`is the car is == "subaru", it predict true`);
console.log( car === `subaru` );
//test 2;
console.log(`is the car is !="toyota, it predict true`);
console.log( car != "toyota");
//test 3;
console.log(`the length of car is == 6, it predict true`);
console.log(car.length ==6);
//test 4;
console.log(`is the name of car tart with "s", it predict with true`);
console.log(car.startsWith(`s`));
//test 5;
console.log(`the name of the car starts with lowercase, it predict true`);
console.log(car.toLowerCase() ==car);
console.log(`/n the above 5 test is false`);
//test 1;
console.log(`is the car name is hyundai, it predict false`);
console.log(car != "subaru");
//test 2;
console.log(`is the car length is !=6, it predict false`);
console.log(car.length !=6);
//test 3;
console.log(`if the name of the car is start with "a", it predict false`);
console.log(car.startsWith(`a`));
//test 4;
console.log(`if the car name is =hyundai, it predict false`);
console.log(car ==`hyundai`);
//test 5;
console.log(`if the car name starts with uppercase ,  it predicts the false`);
console.log(car.toUpperCase() ==car);